<?php

return [
    /**
     * The prefix for all routes in generated by this package.
     */
    'route_prefix' => 'system',

    /**
     *  The field on your user's table where we can determine
     * if the person authenticating is an an admin.
     */
    'permission_field' => 'privileges',

    /**
     * The value we should compare against the premission_column to determine
     * if the person authenticating is an an admin.
     */
    'permission_value' => 'admin',

    /**
     * The disk where your backups will be stored.
     */
    'backup_disk' => 'google',

    /**
     * Absolute paths to all directories that should be backed up.
     * These paths will also be backed up along with all files in your
     * filesystem.links config.
     */
    'paths' => [
    ],

    /**
     * The base seeder that calls all your other seeders
     */
    'base_seeder' => 'DatabaseSeeder',

    /**
     * To receive notifications when the system is modified or backed up, you must
     * provide a slack webhook url.
     */
    'slack_webhook_urls' => [
        'default' => env('SLACK_ALERT_WEBHOOK'),
    ],

    /**
     * The secret token that will be used to authenticate the webhook.
     */
    'webhook_secret' => env('VISUALCONSOLE_WEBHOOK_SECRET'),

    /**
     * The path to the php binary on your server.
     */
    'php_bin' => env('PHP_BINARY', 'php'),
];
